#!/usr/bin/env python3
# -*- coding: utf-8 -*-
class Animal(object):
    def run(self):
        print('Animal is running...')


class Dog(Animal):
    def runa(self):
        print('It is a dog')


class Cat(Animal):
    pass


dog = Dog()
cat = Cat()
print(dog.runa())
print(dog.run())
print(cat.run())
